# 指定环境语言
language: node_js
# 指定sudo权限
sudo: required
# 指定node版本
node_js: stable
# 指定缓存模块，缓存可以加速编译
cache:
  directories:
    - node_modules

# 邮件通知，这里配置不管成功或是失败都通知
notifications:
  email:
    recipients:
      - suxininbeijing@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

# 构建的分支
branches:
  only:
    - master

# 调整时区
before_install:
  - export TZ='Asia/Shanghai'

# 安装环境
install:
  - npm install -g gitbook-cli
  - gitbook install

# gitbook生成静态文件
script:
  - gitbook build

# 生成文件后，进入静态文件目录，部署到指定仓库，需要填写用户名，邮件
after_script:
  - git init
  - git config user.name "suxiaohei"
  - git config user.email "shupaiqianbi@qq.com"
  - git add .
  - git commit -m "Update GitBook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git checkout --orphan gh-pages
  - rm -rf .global_node_modules README.md SUMMARY.md book.json node_modules .travis.yml
  - cp _book/* .
  - rm -rf _book
  - git init
  - git add .
  - git commit -m "Update GitBook By TravisCI With Deploy $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

# 环境变量
env:
 global:
   # Github Pages
   - GH_REF: github.com/suxiaohei/Blog
